// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env["firebase_web_api_key"]!,
    appId: '1:410721668858:web:00978a1377957faa51c343',
    messagingSenderId: '410721668858',
    projectId: 'whatsapp-clone-c01d7',
    authDomain: 'whatsapp-clone-c01d7.firebaseapp.com',
    storageBucket: 'whatsapp-clone-c01d7.appspot.com',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['firebase_android_api_key']!,
    appId: '1:410721668858:android:5170468f3ecd0d3451c343',
    messagingSenderId: '410721668858',
    projectId: 'whatsapp-clone-c01d7',
    storageBucket: 'whatsapp-clone-c01d7.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['firebase_ios_api_key']!,
    appId: '1:410721668858:ios:8b4b59bf00c2564651c343',
    messagingSenderId: '410721668858',
    projectId: 'whatsapp-clone-c01d7',
    storageBucket: 'whatsapp-clone-c01d7.appspot.com',
    iosClientId: '410721668858-emqdr71jkthm5otfmcsq37743aln01i8.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
